---
title: "Assignment4_Lina"
author: "Lina Elkjær Pedersen"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(furrr, purrr, tidyverse, tictoc, R.utils)
```


```{r}
df <- read.delim("AlienData.txt", sep= ",")
```


```{r}

n <- 5
combinations <- sapply(strsplit(intToBin(0:(2 ^ n - 1)), split = ""), paste0, collapse = "")

stimulus <- list()

arms = list()
spots = list()
legs = list()
eyes = list()
color = list()
k = 0

for (i in combinations){
  k = k + 1
  stimulus = append(stimulus, k)
  arms = append(arms, substr(i, 1,1))
  spots = append(spots, substr(i, 2,2))
  legs = append(legs, substr(i, 3,3))
  eyes = append(eyes, substr(i, 4,4))
  color = append(color, substr(i, 5,5))
}



data = data.frame(stimulus_number = unlist(stimulus), arms = unlist(arms), spots = unlist(spots), legs = unlist(legs), eyes = unlist(eyes), color = unlist(color))

data <- data %>%
  mutate(danger = ifelse(spots == 1 & eyes == 1, 1, 0), 
         stimulus_number = as.factor(stimulus_number),
         arms = as.numeric(arms),
         spots = as.numeric(spots), 
         legs = as.numeric(legs),
         eyes = as.numeric(eyes), 
         color = as.numeric(color))

# shuffle the dataframe by rows

set.seed(1993)
shuffled_data_1 = data[sample(1:nrow(data)), ]

set.seed(1997)
shuffled_data_2 = data[sample(1:nrow(data)), ]

set.seed(1999)
shuffled_data_3 = data[sample(1:nrow(data)), ]


experiment <- rbind(shuffled_data_1, shuffled_data_2, shuffled_data_3)


```


Defining similarity and distance
```{r}
# Distance 
distance <- function(vect1, vect2, w) {
  return(sum(w * abs(vect1 - vect2)))
}

# Similarity
similarity <- function(distance, c) {
  return(exp(-c * distance))
}

# # Let's assess similarity
# dd <- tibble(
#   expand_grid(
#     distance = c(0,.1,.2, .3,.4,.5,1,1.5,2,3,4,5,6), 
#     c = c(0.1, 0.2, 0.5, 0.7, 1, 1.5, 2, 3, 4, 5, 6))) %>% 
#   mutate(
#     similarity = similarity(distance, c)
#   )
# 
# dd %>% mutate(c = factor(c)) %>%
#   ggplot() +
#   geom_line(aes(distance, similarity, group = c, color = c)) + 
#   theme_bw()
```


GCM 

```{r}
### generative model ###
gcm <- function(w, c, obs, cat_one, quiet = TRUE) {
  # create an empty list to save probability of saying "1" for each trial
  r <- c()
  
  ntrials <- nrow(obs)
  
  for (i in 1:ntrials) {
    # If quiet is FALSE, print every ten trials
    if (!quiet && i %% 10 == 0) {
      print(paste("i =", i))
    }
    # if this is the first trial, or there any category with no exemplars seen yet, set the choice to random
    if (i == 1 || sum(cat_one[1:(i - 1)]) == 0 || sum(cat_one[1:(i - 1)]) == (i - 1)) {
      r <- c(r, .5)
    } else {
      similarities <- c()
      # for each previously seen stimulus assess distance and similarity
      for (e in 1:(i - 1)) {
        sim <- similarity(distance(obs[i, ], obs[e, ], w), c)
        similarities <- c(similarities, sim)
      }
      # Calculate prob of saying "1" by dividing similarity to 1 by the sum of similarity to 1 and to 2
      numerator <- 0.5 * sum(similarities[cat_one[1:(i - 1)] == 1])
      denominator <- 0.5 * sum(similarities[cat_one[1:(i - 1)] == 1]) + 0.5 * sum(similarities[cat_one[1:(i - 1)] == 0])
      r <- c(r, numerator / denominator)
    }
  }

  return(rbinom(ntrials, 1, r))
}
```






```{r}
 # function for simulation responses
simulate_responses <- function(agent, w, c) {
    
    observations <- experiment %>%
        select(c("arms", "spots", "eyes", "legs", "color"))
    
    danger <- experiment$danger
    
    if (w == "equal") {
      weight <- rep(1 / 2, 2) 
      } 
    else if (w == "optimal" & (experiment$eyes == 1 | experiment$spots == 1)) {
      weight <- rep(1, 2) 
      }
    else {
      weight <- rep(0, 2) 
      }

    # simulate responses
    responses <- gcm(
        weight,
        c,
        observations,
        danger)
    
    tmp_simulated_responses <- experiment %>%
        mutate(
            trial = seq(nrow(experiment)),
            sim_response = responses,
            correct = ifelse(danger == sim_response, 1, 0),
            performance = cumsum(correct) / seq_along(correct),
            c = c,
            w = w,
            agent = agent
        )

    return(tmp_simulated_responses)
}




# simulate responses
plan(multisession, workers = availableCores())

param_df <- dplyr::tibble(
    expand_grid(
        agent = 1:10,
        c = c(0.2, 0.7, 1.2),
        w = c("equal", "optimal")
    )
)

simulated_responses <- future_pmap_dfr(param_df,
    simulate_responses,
    .options = furrr_options(seed = TRUE)
)
```


Subset
```{r}

df_simulated_responses <- simulated_responses %>% 
  subset(c == "0.9" & w == "skewed1")

```



```{r}

ggplot(df_simulated_responses, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line ()+
  facet_wrap(~ df_simulated_responses$agent) + 
  labs(x = "Trial", y = "Performance", color = "Agent")


```


