---
title: "Assignment3_startingup"
author: "Liv Tollånes"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load packages
pacman::p_load(tidyverse, brms, lme4, rlist, rstan, cmdstanr, rstatix, dplyr)
```


```{r}
#Loading in the data
df <- read.table("AlienData.txt", sep = ",")

#Making it into a df
df <- as.data.frame(df)

#Fixing column names
colnames(df) <- as.character(df[1,])

#Now removing first row
df <- df[-1,]

# Create subset of only session 1
unique(df$session) # There are three unique sessions right now
df1 <- subset(df, session == "1")
df1 <- subset(df1, condition == "2")
df1 <- as.data.frame(df1)


df1 <- df1 %>%
  mutate_at(vars(-stimulus), as.numeric)

sapply(df1, class)


# Further inspection
length(unique(df$subject)) # 27 unique subjects in entire data frame

#Check for NAs
NAs <- names(df1)[colSums(is.na(df1)) > 0]
NAs #There are no NAs



# There are some weird trials that should be removed
df1 <- df1[!grepl("pt", df1$stimulus), ]

# code columns for each feature in empiral data
df1 <- df1 %>% 
  mutate(eyes = str_sub(stimulus, 1, 1)) %>% 
  mutate(legs = str_sub(stimulus, 2, 2)) %>% 
  mutate(spots = str_sub(stimulus, 3, 3)) %>% 
  mutate(arms = str_sub(stimulus, 4, 4)) %>% 
  mutate(color = str_sub(stimulus, 5, 5))



#Recoding to delete the nutritious dimension 
df1 <- df1 %>% 
  mutate(response_2 = ifelse(response == 1 | response == 2, 0, 1),
         category_2 = ifelse(category == 1 | category == 2, 0, 1), 
         correct_2 = ifelse(category == response, 1, 0)
         )


df1 <- df1 %>%
  group_by(subject) %>%
  mutate(performance = cumsum(correct_2) / seq_along(correct_2))
```




# Visual exploration

```{r}
# Create the bar plot with the original data frame
barplot(table(df1$correct, df1$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Empirical Data",
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,30),
        border = NA)

# Adjust the subtitle position
title(sub = "Before recoding responses", line = -14.7)

# Add a legend
legend("middle right", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE,
       x = "right",
       y = max(par("usr")[4], par("usr")[3]) + 0.5)


#table(df1$correct) # we see that there are more correct responses than incorrect ones


# Create the bar plot with the reordered data frame
barplot(table(df1$correct_2, df1$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Empirical Data",
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,30),
        border = NA)

# Adjust the subtitle position
title(sub = "After recoding responses", line = -14.7)
# Add a legend
legend("middle right", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE,
       x = "right",
       y = max(par("usr")[4], par("usr")[3]) + 0.5)

```
#Simulated Data
```{r}
# Do it for the simulated data
# Create the bar plot 
barplot(table(simulated_responses$correct, simulated_responses$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Simulated Data", 
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,75),
        border = NA)

# Add a legend
legend("middle right", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE,
       x = "right",
       y = max(par("usr")[4], par("usr")[3]) + 0.5)


#table(simulated_responses$correct) # we see that there are more correct responses than incorrect ones

```



```{r}
# Do it for the simulated data
# Create the bar plot with the reordered data frame
barplot(table(df_simulated_responses_2.2_optimal$correct, df_simulated_responses_2.2_optimal$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Simulated Data", 
        sub = "",
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,15),
        border = NA)

mtext("c = 2.2, w = optimal", side = 3, line = 0.3, cex = 1.1)

# Add a legend
legend("topright", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE)


### Doing it for equal weights
# Do it for the simulated data
# Create the bar plot with the reordered data frame
barplot(table(df_simulated_responses_2.2_equal$correct, df_simulated_responses_2.2_equal$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Simulated Data", 
        sub = "",
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,15),
        border = NA)

mtext("c = 2.2, w = equal", side = 3, line = 0.3, cex = 1.1)

# Add a legend
legend("topright", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE)

#table(simulated_responses$correct) # we see that there are more correct responses than incorrect ones
```


# Simulated data but for different scaling factors
```{r}
# Do it for the simulated data
# Create the bar plot with the reordered data frame
barplot(table(df_simulated_responses_1.2_optimal$correct, df_simulated_responses_1.2_optimal$trial), 
        beside = TRUE, 
        main = "Development of Responses Across Trials - Simulated Data", 
        sub = "",
        ylab = "Response Count",
        xaxt = "t",
        xlab = "Trial Number",
        ylim = c(0,15),
        border = NA)

mtext("c = 1.2, w = Optimal", side = 3, line = 0.3, cex = 1.1)

# Add a legend
legend("right", 
       legend = c("Correct", "Incorrect"), 
       fill = c("light grey", "black"),
       xpd = TRUE)


#table(simulated_responses$correct) # we see that there are more correct responses than incorrect ones
```

# Cumulative Performance Empirical data - per subject
```{r}

df1 <- df1 %>%
  arrange(subject, trial)

ggplot(df1, aes(x = trial, y = performance, color = as.factor(subject))) +
  geom_line ()+
  facet_wrap(~ df1$subject) + 
  labs(x = "Trial", y = "Performance", color = "subject") + 
  stat_summary(aes(group=1), fun.y=mean, geom="line", size = 1)+ ggtitle("Cumulative Performance Empirical Data - Per Subject")

```


```{r}
# Plot - overlapping performance empirical data
ggplot(df1, aes(x = trial, y = performance, color = as.factor(subject))) +
  geom_line () +
  #facet_wrap(~ df_simulated_responses$agent) + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Cumulative Performance - Empirical Data")

```


# Making the performance plots for all weight combinations inb simulated data

#Optimal weights

```{r}
# Optimal weights, c= 0.7
ggplot(df_simulated_responses_07_optimal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Optimal Weights, c = 0.7")

# Optimal weights, c= 1.2
ggplot(df_simulated_responses_1.2_optimal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Optimal Weights, c = 1.2")

# Optimal weights, c= 1.7
ggplot(df_simulated_responses_1.7_optimal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Optimal Weights, c = 1.7")

# Optimal weights, c= 2.2
ggplot(df_simulated_responses_2.2_optimal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Optimal Weights, c = 2.2")
```


#Equal weights

```{r}
# Equal weights, c= 0.2
ggplot(df_simulated_responses_07_equal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Equal Weights, c = 0.7")

#  Equal weights, c= 1.2
ggplot(df_simulated_responses_1.2_equal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Equal Weights, c = 1.2")

#  Equal weights, c= 1.7
ggplot(df_simulated_responses_1.7_equal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Equal Weights, c = 1.7")

#  Equal weights, c= 2.2
ggplot(df_simulated_responses_2.2_equal, aes(x = trial, y = performance, color = as.factor(agent))) +
  geom_line () + 
  labs(x = "Trial", y = "Performance", color = "Agent") +
  stat_summary(geom = "line", fun = "mean", color = "black", size = 1) +
  ggtitle("Equal Weights, c = 2.2")
```


≈